sudo: false

env:
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - travis_retry cabal update

install:
 - cabal --version
 - ghc --version
 - cabal install

script:
 - make test
 - make build

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.1
    - cabal-install-1.18
