sudo: true

language: go

go:
 - 1.5

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
 - docker build -t status-service .
 - docker run --rm -v $(pwd):/build/ status-service
 - ls -alh
