sudo: false

language: haskell

ghc: 7.8

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - ghc --version
 - cabal install

script:
 - make test
 - make build

cache:
  directories:
  - ~/.cabal
